### ISSUE TITLE
KV store related failures and errors

### ISSUE THREAD

**Issue by abronan** [docker/libnetwork#577]
This is an umbrella issue for all the KV store related failures to help addressing those:

- [ ] #576 Persistent Failure of Atomic Operation until docker is restarted
- [ ] #573 Removing containers does not remove entries in overlay network
- [x] #523 Bit sequence handler does not initialize with zookeeper backend
- [x] #438 KV store parameter does not use URI format
- [x] #408 Restarting the KV store causes the CPU to peg at 100%
- [x] #392 Etcd can't be used as a datastore on multi-host
- [ ] #507 Zookeeper, etcd support multiple IPs but datastore.NewClient only takes one
- [ ] #559 docker network create fails with "failed to allocate vxlan id: no bit available"

**Comment by tomdee** [comment]
I just tried using etcd with @mavenugo 's "ux" branch on docker (https://github.com/docker/docker/pull/16645) and hit the following

```
WARN[0159] couldnt create network calico: 104: Not a directory (/docker/libnetwork/network) [26] 
WARN[0159] couldnt cleanup network calico: 104: Not a directory (/docker/libnetwork/network) [26] 
ERRO[0159] Handler for POST /v1.21/networks/create returned error: 104: Not a directory (/docker/libnetwork/network) [26] 
ERRO[0159] HTTP Error                                    err=104: Not a directory (/docker/libnetwork/network) [26] statusCode=500
```

I think this might be tracked by #392

**Comment by abronan** [comment]
@tomdee Thanks for testing this out. Yes this fails because `libnetwork` tries to Watch on something that is considered as a key although you can't watch on a regular key using `etcd`. This defeats the purpose of `libkv` but API v3 is now in the work for `etcd` so that will solve those issues when it's completed and integrated to `libkv`.

I'm poking around libnetwork to try to identify those failures. Have just tried locally and seems to work but if you can try with https://github.com/abronan/libnetwork/tree/ensure_key_is_watchable and confirm with Madhu's work on the new **UX** branch that would be great.

There are other failures related to the way `libnetwork` formats the keys or keep the indexes for the CAS operations. But watching the `network` and `endpoint` directories are the first step.

**Comment by abronan** [comment]
I'm also poking around the new `etcd` client under `coreos/etcd` and I see that there might be some interesting ways to avoid that entirely and maybe solve that issue for good in `libkv` and `libnetwork`.

**Comment by tomdee** [comment]
@abronan I've just tried with your code and I'm still hitting the same problem - 
```
WARN[0037] couldnt create network calico-test2: 104: Not a directory (/docker/libnetwork/network) [87] 
WARN[0037] couldnt cleanup network calico-test2: 104: Not a directory (/docker/libnetwork/network) [87] 
ERRO[0037] Handler for POST /v1.21/networks/create returned error: 104: Not a directory (/docker/libnetwork/network) [87] 
ERRO[0037] HTTP Error                                    err=104: Not a directory (/docker/libnetwork/network) [87] statusCode=500
```

**Comment by abronan** [comment]
@tomdee Maybe flushing the store (`rm` the `default.etcd` folder) could help as the old entry is still there being considered as a Key.

**Comment by tomdee** [comment]
Look like it might be working now :smile:

**Comment by abronan** [comment]
:+1: Anyway this is just a nasty workaround so I'm looking into migrating the codebase to the new `etcd` client and hopefully just a vendor update here will solve the issue :)

**Comment by tomdee** [comment]
OK, I can confirm that this allow me to create networks with a global driver and create containers that use that network.

Workaround or not, it would be great to have etcd working for 1.9! I'm happy to help out with any testing or anything else you can think of.

**Comment by mavenugo** [comment]
thanks @abronan @tomdee.

@tomdee the best help would be to make sure etcd works and stays working :)
@mrjana has recently introduced BATS based multi-host integration tests. (you can check the code under test/ directory). It is currently using consul.

It would be great if you can help enhance that with etcd.
@chenchun would you be willing to contribute zk based tests here ?

that will make sure libnetwork works consistently across these 3 supported KV stores.

**Comment by chenchun** [comment]
@mavenugo Thanks for ping me. Sorry, I'm on vacation at home. Not sure if I have time. I'll have a try tomorrow.

**Comment by abronan** [comment]
@chenchun Get some rest and stay away from computers ;) I'll make sure this works even though we don't find time for integration tests.

**Comment by mavenugo** [comment]
@chenchun yes :) use your vacation wisely. we can enhance integration-tests even during the code-freeze and do continuous improvements to that.

**Comment by abronan** [comment]
@mavenugo We should do a pass on this list and close issues that are fixed. Most of them should be fixed by now.

**Comment by abronan** [comment]
This issue is really old and probably not relevant anymore. I'll close.
